#!/bin.bash
#$ -cwd                 # workingDirectory
#$ -j y
#$ -N Treno
#$ -S /bin/bash
#$ -q all.q@n0002                  # queueName
#$ -pe mpi 1        # cpuNumber
#$ -l h_rt=00:30:00



cd /home/meccanica/abrunelli/Train_2
chmod +x Allrun_cluster
#sort ${PBS_NODEFILE} | uniq -c | awk '{ printf("%s\n", $2); }' > /home/meccanica/abrunelli/mpd.nodes
time ./Allrun_cluster > /home/meccanica/abrunelli/Train_2/output.txt